set_property IOSTANDARD LVCMOS18 [get_ports IO_FPGA_PIN_0_0]
set_property IOSTANDARD LVCMOS18 [get_ports IO_FPGA_PIN_1_0]
set_property IOSTANDARD LVCMOS18 [get_ports IO_FPGA_PIN_2_0]
set_property IOSTANDARD LVCMOS18 [get_ports IO_FPGA_PIN_3_0]
set_property PACKAGE_PIN R19  [get_ports IO_FPGA_PIN_0_0]
set_property PACKAGE_PIN N17  [get_ports IO_FPGA_PIN_1_0]
set_property PACKAGE_PIN P20  [get_ports IO_FPGA_PIN_2_0]
set_property PACKAGE_PIN L17  [get_ports IO_FPGA_PIN_3_0]

set_property IOSTANDARD LVCMOS18 [get_ports O_FPGA_PIN_0_0]
set_property IOSTANDARD LVCMOS18 [get_ports O_FPGA_PIN_1_0]
set_property IOSTANDARD LVCMOS18 [get_ports O_FPGA_PIN_2_0]
set_property IOSTANDARD LVCMOS18 [get_ports O_FPGA_PIN_3_0]
set_property IOSTANDARD LVCMOS18 [get_ports O_FPGA_CLK_0]
set_property IOSTANDARD LVCMOS18 [get_ports O_FPGA_RSTN_0]
set_property IOSTANDARD LVCMOS18 [get_ports O_FPGA_LUT_VITAL_0]
set_property IOSTANDARD LVCMOS18 [get_ports O_FPGA_CHECKER_VITAL_0]
set_property IOSTANDARD LVCMOS18 [get_ports O_FPGA_LOGIC_PROC_VITAL_0]
set_property PACKAGE_PIN P17  [get_ports O_FPGA_PIN_0_0]
set_property PACKAGE_PIN N22  [get_ports O_FPGA_PIN_1_0]
set_property PACKAGE_PIN M21  [get_ports O_FPGA_PIN_2_0]
set_property PACKAGE_PIN J18  [get_ports O_FPGA_PIN_3_0]
set_property PACKAGE_PIN L21  [get_ports O_FPGA_CLK_0]
set_property PACKAGE_PIN T16  [get_ports O_FPGA_RSTN_0]
set_property PACKAGE_PIN D20  [get_ports O_FPGA_LUT_VITAL_0]
set_property PACKAGE_PIN G15  [get_ports O_FPGA_CHECKER_VITAL_0]
set_property PACKAGE_PIN J21  [get_ports O_FPGA_LOGIC_PROC_VITAL_0]

set_property IOSTANDARD LVCMOS18 [get_ports {O_FPGA_PAT_0[*]}]
set_property PACKAGE_PIN K19  [get_ports {O_FPGA_PAT_0[0]}]
set_property PACKAGE_PIN J16  [get_ports {O_FPGA_PAT_0[1]}]
set_property PACKAGE_PIN J20  [get_ports {O_FPGA_PAT_0[2]}]
set_property PACKAGE_PIN B19  [get_ports {O_FPGA_PAT_0[3]}]

set_property IOSTANDARD LVCMOS18 [get_ports O_FPGA_DO_0]
set_property PACKAGE_PIN R20 [get_ports O_FPGA_DO_0]
set_property IOSTANDARD LVCMOS18 [get_ports O_FPGA_OUT_0]
set_property PACKAGE_PIN M19 [get_ports O_FPGA_OUT_0]